config/routes.rb
Rails.application.routes.draw do
  get 'users/profile'

  devise_for :users
  resources :products do
    member do
    put "like", to: "products#upvote"
    end
  end

 root 'products#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  acts_as_votable
 has_attached_file :image, styles: {large: "600x600>", medium: "290x290>", thumb: "150x150#"}
 validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable   #,:confirmable


         has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, except:[:index, :show]
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Cat Was Listed Successfully.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Cat Was Killed Successfully.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @product.upvote_by current_user
    redirect_to :back

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title (page_title)
    content_for (:title) { page_title }
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<title>CATTOPIA <%= yield (:title) %></title>
    <nav class="navbar navbar-default navbar-fixed-top container-fluid">
      <%= link_to 'CATTOPIA', root_path, class: "navbar-brand"%>

      <div class="nav navbar-nav navbar-right ">
              <% if user_signed_in? %>

        <%= link_to 'Add Cat', new_product_path, class: "btn btn-default navbar-btn" %>
        <%= link_to 'My Profile', edit_user_registration_path, class: "btn btn-default navbar-btn" %>
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "btn btn-default navbar-btn" %> <!-- method: :delete delete's user session -->

              <% else %>
        <%= link_to 'Sign In', new_user_session_path, class: "btn btn-default navbar-btn" %>
        <%= link_to 'Register', new_user_registration_path, class: "btn btn-default navbar-btn" %>
        <% end %>


      </div>











    </nav>

<head>
  <title>Store</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

                                  <p class="notice"><%= notice %></p>
                                  <p class="alert"><%= alert %></p>


<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<div class="edit">
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this Cat from being Listed:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
      <br>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
      <br>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
      <br>
  <div class="actions">
    <%= f.submit "Add New Cat" %>
  </div>
<% end %>
</div>

app/views/products/edit.html.erb
<div class="panel panel-default col-md-5 col-md-offset-3">

      <h1 class="panel-heading">Edit Entry</h1>
    <div class="panel-body">
      <%= render 'form' %>
<br>
<div class="btn-group pull-right">
      <%= link_to 'Show', @product, class:"btn btn-default" %>
      <%= link_to 'Back', products_path, class:"btn btn-default" %>
    </div>
    </div>
</div>

app/views/products/index.html.erb
<html>
  <div class="body">
    <div class="jumbotron center"><h1>Welcome to Cattopia</h1>
      <p>Vote For Cute Cats & Kill Ugly Cats ❤ 🐱</p>
    </div>
      <div class="box products transitions-enabled">
        <% @products.each do |product| %>
          <br>
            <div class="product_wrapper panel panel-default"
              <p class="image"> <%=image_tag product.image.url(:medium) %> </p>
              <div class="panel-body">
                <h2 class="title"><%= link_to product.title, product %> </h2>
                <p class="description"><%= truncate product.description, length: 160  %></p> <!--  This cuts the maximum characters allowed in description to 160 -->
                <p class="price">$<%= product.price %></p>
                <div class="btn-group">
                <%= link_to like_product_path(product), method: :put, class: "btn btn-default" do%>
                <span class="glyphicon glyphicon-heart"></span>
                <%= product.get_upvotes.size %>
              <% end %>
                  <% if user_signed_in? %>
                <%= link_to 'Edit', edit_product_path(product), class:"btn btn-default" %>
                <%= link_to 'Kill', product, method: :delete, data: { confirm: 'Murder This Poor Cat??' }, class:"btn btn-default" %>
                <%end %>
              </div>
            </div>
            </div>
        <%end%>
      </div>
    </div>
</html>

app/views/products/new.html.erb
<div class="panel panel-default col-md-5 col-md-offset-3">
<h1 class="panel-heading">New Cat</h1>

    <div class="panel-body">
    <%= render 'form' %>
    <br>
    <%= link_to 'Back', root_path %>
    </div>
  </div>

app/views/products/show.html.erb
<div class=" col-md-5 col-md-offset-3">
<div class="show panel panel-default">

<p id="notice"><%= notice %></p>

<p class="panel-heading"> <%=image_tag @product.image.url(:large) %> </p>
<div class="panel-body">
      <p>
        <strong>Title:</strong>
        <%= @product.title %>
      </p>
      <p>
        <strong>Description:</strong>
        <%= @product.description %>
      </p>
      <p>
        <strong>Price:</strong>
        $<%= @product.price %>
      </p>


<div class="btn-group pull-right">
  <%= link_to like_product_path(@product), method: :put, class: "btn btn-default" do%>
  <span class="glyphicon glyphicon-heart"></span>
  <%= @product.get_upvotes.size %>
<% end %>
  <% if user_signed_in? %>
<%= link_to 'Edit', edit_product_path(@product), class:"btn btn-default" %>
<%= link_to 'Kill', @product, method: :delete, data: { confirm: 'Murder This Poor Cat??' }, class:"btn btn-default" %>
<%= link_to 'Back', root_path,  class:"btn btn-default"%>
 <% end %>
 </div>
 </div>
</div>
</div>